/* ParserNav.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. ParserNav.java */
import java.io.*;
import java.util.*;

public class ParserNav/*@bgen(jjtree)*/implements ParserNavTreeConstants, ParserNavConstants {/*@bgen(jjtree)*/
  protected static JJTParserNavState jjtree = new JJTParserNavState();
        public static LinkedList<Path> querries = new LinkedList<Path>();

        public static void main(String args[]) throws ParseException, IOException {

                // checks args
                if(args.length != 1){
                        System.out.println("Incorrect arguments, correct use:");
                        System.out.println("ParserNav <path of file to be compiled>");
                        System.exit(-1);
                }

                FileInputStream fis = new FileInputStream(new File(args[0]));

                ParserNav parserNav = new ParserNav(fis);
                SimpleNode root = parserNav.ParseExpression();

                System.out.println("\u005cn\u005cnAST:\u005cn");
                root.dump("");
                System.out.println("\u005cn--------");

                exportToFile(root, args[0]);
        }

        public static void exportToFile(SimpleNode root, String filePath) throws IOException{
                System.out.println("Exporting To File\u005cn");

                int index = filePath.lastIndexOf(".");
                String exportFile = filePath.substring(0, index);
                exportFile += "_output";
                exportFile += filePath.substring(index, filePath.length());

                BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(new File(exportFile))));

                int indexAST = 0;
                while(!querries.isEmpty()){
                        Path querry = querries.remove();

                        switch (((SimpleNode) root.jjtGetChild(indexAST)).id) {
                        case ParserNavTreeConstants.JJTTO:
                                bw.write(((To) querry).toString());
                                bw.newLine();
                                bw.newLine();

                                System.out.println((To) querry);
                                System.out.println("\u005cn");
                                break;
                        case ParserNavTreeConstants.JJTCYCLE:
                                bw.write(((Cycle) querry).toString());
                                bw.newLine();
                                bw.newLine();

                                System.out.println((Cycle) querry);
                                System.out.println("\u005cn");
                                break;
                        case ParserNavTreeConstants.JJTSIMPLECYCLE:
                                bw.write(((Cycle) querry).toString());
                                bw.newLine();
                                bw.newLine();

                                System.out.println((Cycle) querry);
                                System.out.println("\u005cn");
                                break;
                        }

                        indexAST++;
                }

                bw.close();
        }

  static final public SimpleNode ParseExpression() throws ParseException {/*@bgen(jjtree) Parse */
                                      SimpleNode jjtn000 = new SimpleNode(JJTPARSE);
                                      boolean jjtc000 = true;
                                      jjtree.openNodeScope(jjtn000);Path obj;
    try {
      ParseExpressionAux();
jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void ParseExpressionAux() throws ParseException {Path obj;
    obj = StartNode();
    jj_consume_token(SEMICOLON);
querries.add(obj);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 0:{
      jj_consume_token(0);
      break;
      }
    case SRC:{
      ParseExpressionAux();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public Path StartNode() throws ParseException {Token t; Path obj;
    jj_consume_token(SRC);
    t = jj_consume_token(VAR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEST:{
      obj = Path(t);
      break;
      }
    case CYCLE:
    case SIMPLECYCLE:{
      obj = Cycle(t);
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return obj;}
    throw new Error("Missing return statement in function");
  }

  static final public To Path(Token t) throws ParseException {/*@bgen(jjtree) To */
                       SimpleNode jjtn000 = new SimpleNode(JJTTO);
                       boolean jjtc000 = true;
                       jjtree.openNodeScope(jjtn000);To obj;
    try {
obj = new To();
                obj.sourceNodeName = t.image;
      DestNode(obj);
      PathCriteria(obj);
jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
{if ("" != null) return obj;}
    } catch (Throwable jjte000) {
if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void DestNode(To obj) throws ParseException {Token t;
    jj_consume_token(DEST);
    t = jj_consume_token(VAR);
obj.destNodeName = t.image;
  }

  static final public void PathCriteria(To obj) throws ParseException {
    OptimalCriteria(obj);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:
    case PASS:{
      RestrictionPath(obj);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
  }

  static final public void OptimalCriteria(Path obj) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MINIMIZE:{
      jj_consume_token(MINIMIZE);
obj.toMinimize = true;
      break;
      }
    case MAXIMIZE:{
      jj_consume_token(MAXIMIZE);
obj.toMinimize = false;
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    Property(obj);
  }

  static final public void Property(Path obj) throws ParseException {Token t;
    t = jj_consume_token(VAR);
obj.attributeFocus = t.image;
  }

  static final public void RestrictionPath(Path obj) throws ParseException {
obj.usePassingRestriction = true;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:{
      jj_consume_token(NOT);
obj.toPass = false;
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    jj_consume_token(PASS);
    RestrictionPathParam(obj);
  }

  static final public void RestrictionPathParam(Path obj) throws ParseException {Token t;
    t = jj_consume_token(VAR);
obj.restrictionPathNodes.add(t.image);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMMA:{
      jj_consume_token(COMMA);
      RestrictionPathParam(obj);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
  }

  static final public Cycle Cycle(Token t) throws ParseException {Cycle obj;
obj = new Cycle();
                obj.sourceNodeName = t.image;
    CycleCondition(obj);
    CycleCriteria(obj);
{if ("" != null) return obj;}
    throw new Error("Missing return statement in function");
  }

  static final public void CycleCondition(Cycle obj) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case CYCLE:{
SimpleNode jjtn001 = new SimpleNode(JJTCYCLE);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(CYCLE);
      } finally {
if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
      }
obj.canRepeatNodes = false;
      break;
      }
    case SIMPLECYCLE:{
SimpleNode jjtn002 = new SimpleNode(JJTSIMPLECYCLE);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(SIMPLECYCLE);
      } finally {
if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
      }
obj.canRepeatNodes = true;
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void CycleCriteria(Cycle obj) throws ParseException {
    Length(obj);
    Property(obj);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:
    case PASS:{
      RestrictionPath(obj);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
  }

  static final public void Length(Cycle obj) throws ParseException {Token t;
    jj_consume_token(MINLENGTH);
    t = jj_consume_token(INT);
obj.minLength = Integer.parseInt(t.image);
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ParserNavTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[8];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x101,0x1a00,0x6000,0x60000,0x2000,0x40,0x1800,0x6000,};
   }

  /** Constructor with InputStream. */
  public ParserNav(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ParserNav(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserNavTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public ParserNav(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserNavTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public ParserNav(ParserNavTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserNavTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[21];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 8; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 21; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
