/* Generated By:JJTree&JavaCC: Do not edit this line. ParserNavConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserNavConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int SRC = 8;
  /** RegularExpression Id. */
  int DEST = 9;
  /** RegularExpression Id. */
  int FIND = 10;
  /** RegularExpression Id. */
  int CYCLE = 11;
  /** RegularExpression Id. */
  int SIMPLECYCLE = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int PASS = 14;
  /** RegularExpression Id. */
  int MINLENGTH = 15;
  /** RegularExpression Id. */
  int NEAREST = 16;
  /** RegularExpression Id. */
  int MAXIMIZE = 17;
  /** RegularExpression Id. */
  int MINIMIZE = 18;
  /** RegularExpression Id. */
  int VAR = 19;
  /** RegularExpression Id. */
  int INT = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\",\"",
    "\";\"",
    "\"src\"",
    "\"dest\"",
    "\"find\"",
    "\"cycle\"",
    "\"simplecycle\"",
    "\"not\"",
    "\"pass\"",
    "\"minlength\"",
    "\"nearest\"",
    "\"maximize\"",
    "\"minimize\"",
    "<VAR>",
    "<INT>",
  };

}
