/* Generated By:JavaCC: Do not edit this line. ParserNavTreeConstants.java Version 6.0_1 */
public interface ParserNavTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTVOID = 1;
  public int JJTTO = 2;


  public String[] jjtNodeName = {
    "Parse",
    "void",
    "To",
  };
}
/* JavaCC - OriginalChecksum=1ddc308d389bce6d0c49e0b0e68eb87f (do not edit this line) */
