/* Generated By:JavaCC: Do not edit this line. ParserNavTreeConstants.java Version 6.0_1 */
public interface ParserNavTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTVOID = 1;
  public int JJTTO = 2;
  public int JJTCYCLE = 3;
  public int JJTSIMPLECYCLE = 4;


  public String[] jjtNodeName = {
    "Parse",
    "void",
    "To",
    "Cycle",
    "SimpleCycle",
  };
}
/* JavaCC - OriginalChecksum=c58ee5a646e18545eab12aaa77491e6a (do not edit this line) */
