/* Generated By:JavaCC: Do not edit this line. ParserNavTreeConstants.java Version 6.0_1 */
public interface ParserNavTreeConstants
{
  public int JJTPARSEEXPRESSION = 0;
  public int JJTSTARTNODE = 1;
  public int JJTPATH = 2;
  public int JJTDESTNODE = 3;
  public int JJTRESTRICTIONPATH = 4;
  public int JJTRESTRICTIONPATHPARAM = 5;
  public int JJTFIND = 6;
  public int JJTCYCLE = 7;
  public int JJTSIMPLECYCLE = 8;
  public int JJTCYCLECRITERIA = 9;
  public int JJTLENGTH = 10;
  public int JJTCRITERIA = 11;
  public int JJTAMOUNT = 12;


  public String[] jjtNodeName = {
    "ParseExpression",
    "StartNode",
    "Path",
    "DestNode",
    "RestrictionPath",
    "RestrictionPathParam",
    "Find",
    "Cycle",
    "SimpleCycle",
    "CycleCriteria",
    "Length",
    "Criteria",
    "Amount",
  };
}
/* JavaCC - OriginalChecksum=1e458e11d5f5b3577add407c583da13f (do not edit this line) */
