/* Generated By:JJTree&JavaCC: Do not edit this line. ParserNavConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserNavConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SRC = 4;
  /** RegularExpression Id. */
  int DEST = 5;
  /** RegularExpression Id. */
  int FIND = 6;
  /** RegularExpression Id. */
  int CYCLE = 7;
  /** RegularExpression Id. */
  int SIMPLECYCLE = 8;
  /** RegularExpression Id. */
  int NL = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int PASS = 12;
  /** RegularExpression Id. */
  int LENGTH = 13;
  /** RegularExpression Id. */
  int SHORTEST = 14;
  /** RegularExpression Id. */
  int CHEAPEST = 15;
  /** RegularExpression Id. */
  int FASTEST = 16;
  /** RegularExpression Id. */
  int NEAREST = 17;
  /** RegularExpression Id. */
  int NODE = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int PROPRIETY = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"src\"",
    "\"dest\"",
    "\"find\"",
    "\"cycle\"",
    "\"simplecycle\"",
    "\"\\n\"",
    "\",\"",
    "\"not\"",
    "\"pass\"",
    "\"length\"",
    "\"shortest\"",
    "\"cheapest\"",
    "\"fastest\"",
    "\"nearest\"",
    "<NODE>",
    "<INT>",
    "<PROPRIETY>",
  };

}
