/* Generated By:JavaCC: Do not edit this line. ParserNavTreeConstants.java Version 6.0_1 */
public interface ParserNavTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTVOID = 1;
  public int JJTSOURCENODE = 2;
  public int JJTPATH = 3;
  public int JJTDESTNODE = 4;
  public int JJTRESTRICTIONPATH = 5;
  public int JJTRESTRICTIONPATHPARAM = 6;
  public int JJTFIND = 7;
  public int JJTCYCLE = 8;
  public int JJTSIMPLECYCLE = 9;
  public int JJTCYCLECRITERIA = 10;
  public int JJTLENGTH = 11;
  public int JJTCRITERIA = 12;
  public int JJTAMOUNT = 13;


  public String[] jjtNodeName = {
    "Parse",
    "void",
    "SourceNode",
    "path",
    "DestNode",
    "restrictionpath",
    "restrictionpathparam",
    "find",
    "cycle",
    "simplecycle",
    "cyclecriteria",
    "length",
    "criteria",
    "amount",
  };
}
/* JavaCC - OriginalChecksum=cb90bbaf0d5ed72f605fcc321e6b869b (do not edit this line) */
