/* Generated By:JavaCC: Do not edit this line. ParserNavTreeConstants.java Version 6.0_1 */
public interface ParserNavTreeConstants
{
  public int JJTPARSEEXPRESSION = 0;
  public int JJTSOURCE = 1;
  public int JJTPATH = 2;
  public int JJTDESTSTM = 3;
  public int JJTCRITERIAPATH = 4;
  public int JJTRESTRICTIONS = 5;
  public int JJTPARAMS = 6;
  public int JJTFIND = 7;
  public int JJTCRITERIAFIND = 8;
  public int JJTTOFIND = 9;
  public int JJTCYCLE = 10;


  public String[] jjtNodeName = {
    "ParseExpression",
    "Source",
    "Path",
    "DestStm",
    "CriteriaPath",
    "Restrictions",
    "Params",
    "Find",
    "CriteriaFind",
    "ToFind",
    "Cycle",
  };
}
/* JavaCC - OriginalChecksum=f22b080177d082807616a8f6b6e91081 (do not edit this line) */
