/* Generated By:JJTree&JavaCC: Do not edit this line. ParserNavConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserNavConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DSLSTART = 4;
  /** RegularExpression Id. */
  int DSLEND = 5;
  /** RegularExpression Id. */
  int SRC = 6;
  /** RegularExpression Id. */
  int DEST = 7;
  /** RegularExpression Id. */
  int FIND = 8;
  /** RegularExpression Id. */
  int CYCLE = 9;
  /** RegularExpression Id. */
  int SIMPLECYCLE = 10;
  /** RegularExpression Id. */
  int NL = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int PASS = 14;
  /** RegularExpression Id. */
  int LENGTH = 15;
  /** RegularExpression Id. */
  int SHORTEST = 16;
  /** RegularExpression Id. */
  int CHEAPEST = 17;
  /** RegularExpression Id. */
  int FASTEST = 18;
  /** RegularExpression Id. */
  int NEAREST = 19;
  /** RegularExpression Id. */
  int NODE = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int PROPRIETY = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"/**@navqdsl\"",
    "\"@navqdsl**/\"",
    "\"src\"",
    "\"dest\"",
    "\"find\"",
    "\"cycle\"",
    "\"simplecycle\"",
    "\"\\n\"",
    "\",\"",
    "\"not\"",
    "\"pass\"",
    "\"length\"",
    "\"shortest\"",
    "\"cheapest\"",
    "\"fastest\"",
    "\"nearest\"",
    "<NODE>",
    "<INT>",
    "<PROPRIETY>",
  };

}
