/* Generated By:JJTree&JavaCC: Do not edit this line. ParserNavConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserNavConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NL = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int SRC = 6;
  /** RegularExpression Id. */
  int DEST = 7;
  /** RegularExpression Id. */
  int SHORTEST = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int PASS = 10;
  /** RegularExpression Id. */
  int HIGH = 11;
  /** RegularExpression Id. */
  int LOW = 12;
  /** RegularExpression Id. */
  int NODE = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\",\"",
    "\"src\"",
    "\"dest\"",
    "\"shortest\"",
    "\"not\"",
    "\"pass\"",
    "\"high\"",
    "\"low\"",
    "<NODE>",
  };

}
